/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chingo.demo.service;

public class ServiceApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ServiceApplication().getGreeting());
    }
}
