/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chingo.demo.web;

import org.junit.jupiter.api.Test;

class WebApplicationTest {
    @Test void appHasAGreeting() {
    }
}
