server:
  port: 8080
spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://192.168.61.101:53306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: demo
    password: demo

logging:
  level:
    org.chingo.demo.web: debug