/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.chingo.web;

public class AppMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new AppMain().getGreeting());
    }
}
